# Generated by Django 4.2.27 on 2025-12-05 12:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Movie Title')),
                ('director', models.CharField(max_length=200, verbose_name='Director')),
                ('screenwriter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Screenwriter')),
                ('cast', models.TextField(verbose_name='Cast (comma-separated)')),
                ('genre', models.CharField(max_length=100, verbose_name='Genre (e.g., Drama/Action/Comedy)')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('runtime', models.PositiveIntegerField(verbose_name='Runtime (minutes)')),
                ('plot_summary', models.TextField(verbose_name='Plot Summary')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='IMDB Rating (0-10)')),
                ('language', models.CharField(default='English', max_length=50, verbose_name='Original Language')),
                ('country', models.CharField(max_length=100, verbose_name='Country of Origin')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is Public')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movie Management',
                'ordering': ['-release_date', '-created_at'],
            },
        ),
    ]
